batch_size: 256
max_iter: 50000
lr: 0.001
lr_min: 0.0001
log_every: 10
val_every: 1000
val_num: 10
save_every: 5000
grad_clip: 10.0

test_grasp_num: 100
test_topk: 10

model:
  name: BaseModel
  backbone:
    name: WrappedMinkUNet
    out_feat_dim: 1024
    voxel_size: 0.005
  grasp_type_emb:
    name: LearnableTypeCond
    out_feat_dim: 128
    disabled: False
  head:
    name: FlowRT_MLPRTJ
    in_feat_dim:
    joint_num:  ${....hand.joint_num}
    traj_length: ${....data.traj_length}
    diffusion:
      ode: 1
      scheduler_type: DDIMScheduler
      scheduler:
        beta_schedule: squaredcos_cap_v2
        prediction_type: v_prediction
        num_train_timesteps: 128
        clip_sample: False
      num_inference_timesteps: 10
      log_prob_type: accurate_cont
      loss_type: l1
 
loss_weight:
  loss_diffusion: 1.0  
  loss_trans: 1.0
  loss_rot: 1.0
  loss_joint: 1.0 